### ISSUE TITLE
Still asking for a License Key

### ISSUE THREAD

**Issue by jannisg** [jamierumbelow/taggable#1]
Hi Jamie,

I think it's a great move to open-source this project and let the community take over support for future revisions of EE.

One note however is that this current open source version is still asking for a license key when used right now:

`Your license key is: ENTER YOUR LICENSE KEY HERE`

You may want to take that bit out as part of the open-sourcing process :)

Cheers!

**Comment by jamierumbelow** [comment]
Very good point, thanks for letting me know!
