### ISSUE TITLE
Residual license key bug

### ISSUE THREAD

**Issue by jujudigital** [jamierumbelow/taggable#2]
Hi Jamie,

I've just installed this on a development system and there is still a residual license key related bug.

I'm new to GitHub - I've forked and fixed not sure if that's the correct protocol. My apologies if I shouldn't have.
I've removed residual references to $license_key from followng files:
 ~/views/cp/index.php
~/views/cp/preferences.php

Cheers,
Alex

**Comment by jamierumbelow** [comment]
Fix away!  

Jamie Rumbelow

jamie@jamierumbelow.net

**Comment by jujudigital** [comment]
Cheers done it ref pull request.
